services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_secure_password
      POSTGRES_DB: fitnesstracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./FitnessTrackerBack  # Изменили контекст!
      dockerfile: Dockerfile
    volumes:
      - ./FitnessTrackerBack:/app/FitnessTrackerBack
    ports:
      - "5024:5024"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=fitnesstracker;Username=postgres;Password=my_secure_password
    depends_on:
      - db

volumes:
  postgres_data:



































