services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_secure_password
      POSTGRES_DB: fitnesstracker
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -u postgres"]
       interval: 5s
       timeout: 5s
       retries: 5

  backend:
    build:
      context: ./FitnessTrackerBack  
      dockerfile: Dockerfile
    volumes:
      - ./fitnesstrackerback:/app/fitnesstrackerback
    ports:
      - "5024:5024"
    environment:
      - aspnetcore_environment=development
      - connectionstrings__defaultconnection=host=db;port=5432;database=fitnesstracker;username=postgres;password=my_secure_password
    depends_on:
      - db

volumes:
  postgres_data:



























































